name: ScanCode Toolkit Scan

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  scancode-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y unzip wget

      - name: Download and extract ScanCode Toolkit
        run: |
          wget https://github.com/nexB/scancode-toolkit/releases/download/v30.1.0/scancode-toolkit-30.1.0.zip -O scancode-toolkit.zip
          unzip scancode-toolkit.zip
          chmod +x ./scancode-toolkit-30.1.0/scancode

      - name: Run ScanCode Scan (Full Dependency and License Scan)
        run: |
          ./scancode-toolkit-30.1.0/scancode --info --json-pp scan-results.json ./

      - name: Upload Scan Results
        uses: actions/upload-artifact@v3
        with:
          name: scan-results
          path: scan-results.json
