name: Scanoss Toolkit Scan

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  scancode-scan:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Ensure summary.md exists and display it in the workflow summary
      - name: Display Results and Charts in Workflow Summary
        run: |
          if [ -f summary.md ]; then
            cat summary.md >> $GITHUB_STEP_SUMMARY
          else
            echo "summary.md not found." >> $GITHUB_STEP_SUMMARY
          fi
