name: ScanCode Toolkit Scan

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  scancode-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y wget tar python3 python3-pip

      - name: Download and extract ScanCode Toolkit
        run: |
          wget https://github.com/aboutcode-org/scancode-toolkit/releases/download/v32.3.1/scancode-toolkit-v32.3.1_py3.10-linux.tar.gz -O scancode-toolkit.tar.gz
          tar -xvf scancode-toolkit.tar.gz
          mv scancode-toolkit-* scancode-toolkit
          chmod +x ./scancode-toolkit/scancode
          pip install scanoss

      - name: Run ScanCode Scan (Full Dependency and License Scan)
        run: |
          scanoss-py dep -o results.json ./

    
