name: SCANOSS Dependency Scan Workflow
run-name: "SCANOSS Dependency Scan Run by ${{ github.actor }}"

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:  # Allows manual trigger from Actions tab

jobs:
  scanoss-dependency-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install SCANOSS CLI
        run: python -m pip install scanoss

      - name: Run SCANOSS Dependency Scan with --trace
        id: scanoss-scan
        run: |
          scanoss-py dependencies ./ --trace
