name: Scanoss Toolkit Scan

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  scancode-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Display Results and Charts in Workflow Summary
        run: |
         cat summary.md >> $GITHUB_STEP_SUMMARY
